/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as CategoryGenreRouteImport } from './routes/category.$genre'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryGenreRoute = CategoryGenreRouteImport.update({
  id: '/category/$genre',
  path: '/category/$genre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/live': typeof LiveRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/watch': typeof WatchRoute
  '/category/$genre': typeof CategoryGenreRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/live': typeof LiveRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/watch': typeof WatchRoute
  '/category/$genre': typeof CategoryGenreRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/live': typeof LiveRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/watch': typeof WatchRoute
  '/category/$genre': typeof CategoryGenreRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/live'
    | '/search'
    | '/shorts'
    | '/watch'
    | '/category/$genre'
    | '/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/live'
    | '/search'
    | '/shorts'
    | '/watch'
    | '/category/$genre'
    | '/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/live'
    | '/search'
    | '/shorts'
    | '/watch'
    | '/category/$genre'
    | '/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LiveRoute: typeof LiveRoute
  SearchRoute: typeof SearchRoute
  ShortsRoute: typeof ShortsRoute
  WatchRoute: typeof WatchRoute
  CategoryGenreRoute: typeof CategoryGenreRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$genre': {
      id: '/category/$genre'
      path: '/category/$genre'
      fullPath: '/category/$genre'
      preLoaderRoute: typeof CategoryGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LiveRoute: LiveRoute,
  SearchRoute: SearchRoute,
  ShortsRoute: ShortsRoute,
  WatchRoute: WatchRoute,
  CategoryGenreRoute: CategoryGenreRoute,
  ChannelChannelIdRoute: ChannelChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
